database:
  host: 192.168.1.1
  port: 3306
  username: root
  password: supersecret
  name: production_db

server:
  host: 127.0.0.1
  port: 8080

features:
  enableSignup: false
  maxUsers: 1000

logging:
  level: info
  file: /var/log/app2.log
